import cl from 'clsx';

import useVariables from '../../../context/useVariables';
import { getConfig } from '../../../util/config/getConfig';
import classes from './NotesTab.module.scss';
import {
  getNotes,
  MandatoryNotes,
  NonMandatoryNotes,
  NoNotes,
  PxTableMetadata,
  SymbolExplanationNotes,
  Variable,
} from '@pxweb2/pxweb2-ui';

export type NotesTabProps = {
  readonly pxTableMetadata: PxTableMetadata | undefined;
};

/**
 * Checks if the given table have any notes.
 *
 * @param pxTableMetadata - The metadata object of the Px table, which can be null or undefined.
 * @returns `true` if the table have any notes, otherwise `false`.
 */
function tableHasAnyNotes(
  pxTableMetadata: PxTableMetadata | null | undefined,
): boolean {
  if (!pxTableMetadata) {
    return false;
  }

  // Any notes at table level?
  if (hasNotesAtTableLevel(pxTableMetadata)) {
    return true;
  }

  if (pxTableMetadata.variables) {
    for (const variable of pxTableMetadata.variables) {
      if (variableHasAnyNotes(variable)) {
        return true;
      }
    }
  }

  return false;
}

function hasNotesAtTableLevel(
  pxTableMetadata: PxTableMetadata | undefined,
): boolean {
  if (!pxTableMetadata) {
    return false;
  }
  return pxTableMetadata.notes && pxTableMetadata.notes.length > 0;
}

/**
 * Checks if a given variable or any of its values have notes.
 *
 * @param {Variable} variable - The variable to check for notes.
 * @returns {boolean} - Returns `true` if the variable or any of its values have notes, otherwise `false`.
 */
function variableHasAnyNotes(variable: Variable): boolean {
  // Any notes at variable level?
  if (variable.notes && variable.notes.length > 0) {
    return true;
  }
  if (variable.values) {
    // Any notes at variable level?
    for (const value of variable.values) {
      if (value.notes && value.notes.length > 0) {
        return true;
      }
    }
  }

  return false;
}

/**
 * Get a copy of the "total metadata" with only the variables and values that are present in the selection.
 *
 * @param totalMetadata - The total metadata of the table.
 * @param selection - The selection of variables and values.
 * @returns A copy of the total metadata with only the variables and values that are present in the selection.
 */
function getMetadataCopyForSelection(
  totalMetadata: PxTableMetadata,
  selection: PxTableMetadata,
): PxTableMetadata {
  const totalMetadataCopy = structuredClone(totalMetadata);

  // Create a map of variable ids and their value codes in the selection for quick lookup
  const selectionVariableValueMap = new Map<string, Set<string>>();
  if (selection.variables) {
    for (const variable of selection.variables) {
      const valueCodes = new Set<string>();
      if (variable.values) {
        for (const value of variable.values) {
          valueCodes.add(value.code);
        }
      }
      selectionVariableValueMap.set(variable.id, valueCodes);
    }
  }

  // Filter out variables in totalMetadataCopy that are not present in the selection
  totalMetadataCopy.variables = totalMetadataCopy.variables.filter((variable) =>
    selectionVariableValueMap.has(variable.id),
  );

  // Filter out values in each variable that are not present in the selection
  totalMetadataCopy.variables.forEach((variable) => {
    const selectedValues = selectionVariableValueMap.get(variable.id);
    if (selectedValues) {
      variable.values = variable.values.filter((value) =>
        selectedValues.has(value.code),
      );
    } else {
      variable.values = [];
    }
  });

  return totalMetadataCopy;
}

export function NotesTab({ pxTableMetadata }: NotesTabProps) {
  const pxMetaTotal = useVariables(); // All metadata for table

  if (!pxMetaTotal.pxTableMetadata || !pxTableMetadata) {
    return <NoNotes tableLevel={true} />; // No notes on entire table;
  }

  // Get metatadata from "Total metadata" for the part (variables and values) that is selected by the user
  const metadataCopyForSelection = getMetadataCopyForSelection(
    pxMetaTotal.pxTableMetadata,
    pxTableMetadata,
  );

  // Check if there are any notes at all in the total metadata
  if (!tableHasAnyNotes(pxMetaTotal.pxTableMetadata)) {
    // If there are no notes at all in the total metadata, we can still have an autogenerated note
    // at table level from the data API-call. This can happen if we have special characters in the table (.. = means no data)
    // Check if we have any autogenerated notes at table level.
    if (!hasNotesAtTableLevel(pxTableMetadata)) {
      return <NoNotes tableLevel={true} />; // No notes on entire table
    }
  }

  if (!tableHasAnyNotes(metadataCopyForSelection)) {
    return <NoNotes tableLevel={false} />; // No notes for this specific selection
  }

  const config = getConfig();
  const specialCharacters = config.specialCharacters;
  const notes = getNotes(
    metadataCopyForSelection,
    pxTableMetadata,
    specialCharacters,
  );

  return (
    <div className={cl(classes.notesTab)}>
      {Object.keys(notes.SymbolExplanationNotes).length > 0 && (
        <SymbolExplanationNotes notes={notes.SymbolExplanationNotes} />
      )}
      {notes.mandatoryNotes.notesCount > 0 && (
        <MandatoryNotes notes={notes.mandatoryNotes} />
      )}
      {notes.nonMandatoryNotes.notesCount > 0 && (
        <NonMandatoryNotes notes={notes.nonMandatoryNotes} />
      )}
    </div>
  );
}
