# .github/workflows/chromatic.yml

name: 'Chromatic'

on:
  push:
    branches:
      - main
    paths:
      - 'packages/pxweb2-ui/**'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/pxweb2-ui/**'

permissions:
  contents: read

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build style-dictionary
        run: npm run build-style-dictionary

      - name: Publish to Chromatic
        uses: chromaui/action@534eebfc19023579541d106f7b61d5ad70ed65c7 # v18.5.0
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
